### ISSUE TITLE
[BUG] could not be found, replacing a question mark

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-radialmenu#105]
**Describe the bug**
console.error(`Icon "${link}" could not be found, replacing a question mark.`);
svg.setAttribute('viewBox', `0 0 ${icos[link][0]} ${icos[link][1]}`);

in RadialMenu js

**To Reproduce**
1. Go to use F1 and i get 2 error in f8
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

<a href="https://ibb.co/1L30dkR"><img src="https://i.ibb.co/W6QHPLB/rerror.png" alt="rerror" border="0"></a>

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by Flying-Turtles2** [comment]
I had the same issue so I went back and the Dev Version is working properly

**Comment by Andyauk** [comment]
> I had the same issue so I went back and the Dev Version is working properly

I put my backup copy In.

**Comment by RestrictedNova** [comment]
This should solve the errors^

**Comment by Andyauk** [comment]
> This should solve the errors^

thanks. going to check now.
