### ISSUE TITLE
qb-radialmenu, when you go to General, then Clothing, Then hit extra. i get a error in the f8 consol.

### ISSUE THREAD

**Issue by McNastty6699** [qbcore-framework/qb-radialmenu#107]
![image](https://user-images.githubusercontent.com/88422603/170413689-bb183f9b-8714-4794-8225-89a6e0c5cd48.png)

**Comment by Branqueador** [comment]
still happens , any fix?

**Comment by NylanderrDK** [comment]
I get the same error.

**Comment by peppinoita** [comment]
replace shopping-bag with bag-shopping

`icon = 'bag-shopping',`

**Comment by sinphoenix** [comment]
Did your error get fixed?

**Comment by Millusion** [comment]
> 

this works. change the shopping-bag icon to bag-shopping in botht he js file as in the config and it's fixed

**Comment by Adonislee94** [comment]
im getting the same error but it says "tshirt"
