### ISSUE TITLE
Static Radialmenu

### ISSUE THREAD

**Issue by itsjustyoan** [qbcore-framework/qb-radialmenu#108]
is there a way to keep it static once i press F1, instead of holding the button down?

**Comment by nggcasey** [comment]
Used to be a feature, don't know what stopped it?

**Comment by Dwohakin** [comment]
uhh would be cool to have it back ngl

**Comment by strongprincess** [comment]
this would be amazing to have back

**Comment by chunce01** [comment]
Go into the main js file and delete this at the bottom, problem solved:

$(document).on('keyup', function(e) {
    QBRadialMenu.close();
});
