### ISSUE TITLE
[BUG] Cant use Clothing in F1

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-radialmenu#109]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to '...' F1 and the clothing section take off glasses or hat. nothing happens.
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
when you click F1 and go to clothing you should be able to use it.

**Screenshots**
tba

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] Latest
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] 
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by Andyauk** [comment]
seems some of the images has not been changed in clothing after looking.

**Comment by Andyauk** [comment]
bag-shopping
masks-theater

**Comment by sinphoenix** [comment]
Still getting this issue?
