### ISSUE TITLE
[BUG] can't use objects menu in F1

### ISSUE THREAD

**Issue by Snip12** [qbcore-framework/qb-radialmenu#110]
I cant use the Objects Menu in F1

**Comment by nggcasey** [comment]
Confirmed - Client console error

[   1310594] [b2372_GTAProce]        CrBrowserMain/ Icon "sign" could not be found, replacing a question mark. (@qb-radialmenu/html/js/RadialMenu.js:387)
[   1310594] [b2372_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read property '0' of undefined (@qb-radialmenu/html/js/RadialMenu.js:403)

https://www.youtube.com/watch?v=ap0h88B4sJU&ab_channel=CaseyReed

**Comment by nggcasey** [comment]
Confirmed this pull request fixes it

https://github.com/qbcore-framework/qb-radialmenu/pull/112

**Comment by uShifty** [comment]
Appears to be resolved, Reopen if the issue is not fixed
