### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jokernights** [qbcore-framework/qb-radialmenu#111]
**Describe the bug**
When down I can't do anything, I used to be able to use the radial menu under police for the emergency button .. but i get this error and can't even open my chat

**To Reproduce**
1. Go to 'F1'
2. Click on 'nothing to click on '
3. Use this item '....' n/a
5. See error

![image](https://user-images.githubusercontent.com/77025615/171325482-b25d32cf-e76d-40fe-9a52-1be38d045d26.png)

**Expected behavior**
for radial menu to work properly 

**Screenshots**
above

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 5 minutes ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] zdiscord qb-target 
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
I saw some issues with this and figured if i updated and had an undoctored version it would fix the issue.

**Comment by JordanBScott** [comment]
How'd you fix it?

**Comment by ChurchTG7** [comment]
i'd like to know aswell
