### ISSUE TITLE
[BUG] Clothing.lua Error

### ISSUE THREAD

**Issue by JordanBScott** [qbcore-framework/qb-radialmenu#117]
**Describe the bug**
When going through the F1 menu to change clothing (F1>General>Clothing>Shirt) and take off my characters shirt, it works, but then when I do the same to put it back on, I get the error seen in the screenshot.

**To Reproduce**
1. Go to 'F1 Menu'
2. Click on 'General'
3. Click on 'Clothing'
4. Click on 'Shirt' (shirt comes off character)
5. Repeat steps 1-4 (to put shirt back on)
6. See error

**Expected behavior**
To have characters shirt put back on

**Screenshots**
![Screenshot (438)](https://user-images.githubusercontent.com/99845881/174722791-677df571-9c5a-4cb7-bf2c-ab7e378aa1ec.png)

**Questions (please complete the following information):**
 - When you last updated: Last Week
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
None at the moment

**Comment by bosskitz** [comment]
Having the same issue.
Commented lines 702 - 706 in the client.lua temporarily fixed this and remade it so it would include Drawables 8, 3 and 10.

**Comment by JordanBScott** [comment]
> 

Gotcha. Are you talking about the clothing.lua in the client folder? 
			Extra = {
				{Drawable = 8, Id = 15, Tex = 0, Name = "Extra Undershirt"},
				{Drawable = 3, Id = 15, Tex = 0, Name = "Extra Gloves"},
				{Drawable = 10, Id = 0, Tex = 0, Name = "Extra Decals"},
				}
Comment this out?
And what do you mean you remade it so it would include Drawables 8, 3, and 10?

**Comment by sinphoenix** [comment]
still getting this error?

**Comment by sinphoenix** [comment]
No response on error.. Could not reproduce on my end
