### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kingofkingzcd** [qbcore-framework/qb-radialmenu#127]
is this ever gonna get fixed? clothing doesnt work at all with new radial menu pull. no commands. doesnt work in the actual menu. no errors. no custom file names etc. this has been broken for AGES.

**Comment by kingofkingzcd** [comment]
![image](https://user-images.githubusercontent.com/83891867/180147435-764c12da-dbf5-40f5-9839-4f0168c52c4d.png)

**Comment by kingofkingzcd** [comment]
nvm theres the error keeping it from working

**Comment by kingofkingzcd** [comment]
![image](https://user-images.githubusercontent.com/83891867/180149783-a616f29a-a21d-41ed-8d67-496734d74cc6.png)

**Comment by kingofkingzcd** [comment]
whole thing is nothing but clothing related errors. fix one and 10 more show up.

**Comment by sinphoenix** [comment]
Are you using a custom clothing pack? if so, try removing that and see if that fixes it

>> Have you editing Radial menu?
>> Custom clothing pack?

**Comment by sinphoenix** [comment]
Errors still happening?? If so, did what i tell you to try fix it?
