### ISSUE TITLE
[BUG] Both (Extra items) Gloves and Visor not working + errors

### ISSUE THREAD

**Issue by rxnm** [qbcore-framework/qb-radialmenu#135]
**Describe the bug**
So using both extra options in the radialmenu (gloves) "error 1 in config" and (visor) "error 2 in config" doesn't do anything but shows an error in the logs.

**To Reproduce**
1. Go to 'Radialmenu, clothing, extras, open gloves or visor and both dont do anything, then check logs.'
2. See error (image below)
https://imgur.com/uAT81f4

**Expected behavior**
Of course to open the selected item as the tip shows.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/uAT81f4)

**Questions (please complete the following information):**
 - When you last updated: [recent update]
 - Are you using custom resource? which ones? [tried both with and without custom resources running]
 - Have you renamed `qb-` to something custom? [nope]

**Additional context**
N/A

**Comment by Pilouxs** [comment]
Hello, at line 723 in qb-radialmenu/client/clothing, change "visor" to "Visor" and i think the problem is similar for "Gloves" :)

**Comment by Irishstevie** [comment]
try #145 This may fix your issue and let us know :)

**Comment by dexter9006** [comment]
> Hello, at line 723 in qb-radialmenu/client/clothing, change "visor" to "Visor" and i think the problem is similar for "Gloves" :)

Works perfetly ✅
