### ISSUE TITLE
[BUG] /putintrunk notifies the kidnapped player trunk is closed

### ISSUE THREAD

**Issue by Bolbolito** [qbcore-framework/qb-radialmenu#142]
**Describe the bug**
/putintrunk command notifies the kidnapped player trunk is closed even when the trunk is open.

**To Reproduce**
1. Kidnap a player.
2. Get near a vehicle with an open trunk.
3. Use /putintrunk command.
4. Drops kidnapped player.
5. Kidnapped player receives the notification trunk is closed.

**Expected behavior**
The kidnapped player should enter the trunk when open.

**Questions (please complete the following information):**
 - When you last updated: Latest Resources
 - Are you using custom resource? which ones? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
Been trying to fix this but can't make it work.

**Comment by ChickenDipper1** [comment]
Same issue here
