### ISSUE TITLE
Radial menu gets stuck on a cursor when closed

### ISSUE THREAD

**Issue by SelfishEagle** [qbcore-framework/qb-radialmenu#149]
**Describe the bug**
Radial menu opens fine but when it closes cursor gets stuck on screen and characters can not move

**Screenshots**

https://gyazo.com/9bfe766ff59c391f7711c6c7c9c756f7

**Questions (please complete the following information):**
 - When you last updated: Most Recent
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] No

**Comment by ivoprodavadeca2** [comment]
Do you fixed that ? 
because i have the same problem
