### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by Vareska** [qbcore-framework/qb-radialmenu#152]
fresh install of qb-radialmenu and this error comes up in the console when ingame

![image](https://github.com/qbcore-framework/qb-radialmenu/assets/6834727/4cabd91b-fde5-49cf-92fa-cb3fe820a002)

**Comment by KeeganAI** [comment]
> fresh install of qb-radialmenu and this error comes up in the console when ingame
> 
> ![image](https://user-images.githubusercontent.com/6834727/246167076-4cabd91b-fde5-49cf-92fa-cb3fe820a002.png)

hey, did you just start the server? 
let me know how to reproduce it.

**Comment by Vareska** [comment]
It was a full clean reinstall with the updated radial menu and the error happens every time you load the server

**Comment by KeeganAI** [comment]
i could just suggest to re-install the entire framework, i didnt get that error...

**Comment by Vareska** [comment]
Thats what I did to get the error lol

**Comment by KeeganAI** [comment]
i just did the same thing, i dont get it

**Comment by tomigatica15** [comment]
They updated the script, download it again and let me know
