### ISSUE TITLE
[BUG] - Interactions not working

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-radialmenu#172]
**Describe the bug**
Framework: Newest style of QBCore framework, roughly 1 month old

Escort, Rob & Hostage isn't working at all for me. Both myself and my friend are set as unemployed grade 0 and neither of us are getting the 3 things working on each other

**Expected behavior**
For them to work

**Screenshots**
Unable to provide cause it doesn't show it not working

**Questions (please complete the following information):**
 - When you last updated: - Just, fresh new install 
 - Are you using custom resource? - No
 - Have you renamed `qb-` to something custom? - Definitely Not

**Additional context**
Any help or guidance would be appreciated

**Comment by SinisterDevelopment** [comment]
i just installed fresh copy and cant get this to happen! Can you please try to replace the script with the newer version and let me know if that fixed it
