### ISSUE TITLE
Menu/Cursor Issue

### ISSUE THREAD

**Issue by Scott1sh** [qbcore-framework/qb-radialmenu#18]
If you click the centre menu too fast it will freeze the player UI and the script needs to be restarted

Possibly needs a small timeout to prevent spam clicking

How to replicate
Open Radial menu
Navigate to 2 or 3 sub-menus
Click the back icon very fast and then click the close icon

**Comment by GhzGarage** [comment]
Could not replicate

**Comment by BerkieBb** [comment]
I could replicate it

**Comment by BerkieBb** [comment]
But it's not easy to replicate somehow

**Comment by IdrisDose** [comment]
For me if the radial lags for whatever reason when closing the NUI focus doesn't get triggered.

**Comment by GhzGarage** [comment]
It should be fixed now
