### ISSUE TITLE
[Issue?] Config.ExtrasEnabled = true/false doens't work

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-radialmenu#26]
I noticed Config.ExtrasEnabled = true is in the conig.lua, however setting it to false I assume that the vehicle extras menu is supposed to be hidden or similar? If it is, it's not working when set to false.

I also tried commenting out the extras block line 352 to 450 and it causes F1 too throw an error when inside a car: https://discord.com/channels/831626422232678481/868498482359582741/884984198581080125

I then commented out line 357 to 448 and that stops the use of extras, but the F1 menu for it still exists, just shows blank. So im not sure how to make the "vehicle extras" button go away.

Not sure if it's just a bug or such?

**Comment by HATE-dev** [comment]
Config.Extrasenabled is not for vehicle extras, its jst for clothing commands. You have to comment out config.lua line 349 to  446 then you have to change  " Config.MenuItems[3].items[3].items = {" to " Config.MenuItems[3].items[2].items = {" all of them

**Comment by nzkfc** [comment]
Yeah already did all that, I guess the name needs to be changed to something more relevant or just add in the commented line about it's use.

**Comment by GhzGarage** [comment]
discord.gg/qbcore for support on this
