### ISSUE TITLE
qb-radicalmenu does not open after updating

### ISSUE THREAD

**Issue by masutto** [qbcore-framework/qb-radialmenu#56]
Hey everyone, i just downloaded this script at 6:30pm Est tonight 1/12/22 and im getting these errors after drag and drop to update the menu. ive also downloaded the Locales file and put in qb-core\shared and im experiencing these errors:

![qb-radialmenu error PNG](https://user-images.githubusercontent.com/28587596/149249287-60896427-c122-49d9-a312-66533d50f909.PNG)

qb-radialmenu\client\main.lua

`RegisterCommand('radialmenu', function()
(Line 6--->) if not PlayerData.metadata["isdead"] and not PlayerData.metadata["inlaststand"] and not PlayerData.metadata["ishandcuffed"] and not IsPauseMenuActive() and not inRadialMenu then
        openRadial(true)
        SetCursorLocation(0.5, 0.5)
    end
end)`

If i do "refresh, and ensure qb-radicalmenu" in the console it gives me this:

![qb-radialmenu error 2](https://user-images.githubusercontent.com/28587596/149249230-a826290e-9e38-4397-ac9e-34d9f8f8d5a1.PNG)

` -- Sets the metadata when the player spawns (<----Line 14)
RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
    PlayerData = QBCore.Functions.GetPlayerData()
end)`

**Comment by BerkieBb** [comment]
Just loaded in my server and it works, make sure qb-core starts before the radialmenu and you have the locale.lua file in qb-core/shared
