### ISSUE TITLE
Can't Open RadialMenu When Dead

### ISSUE THREAD

**Issue by MarcusPlayz517** [qbcore-framework/qb-radialmenu#80]
My whole server can't open the F1 wheel when dead as EMS, Police. (for panic button) Any fixes?

**Comment by NoobySloth** [comment]
> 

You could do this;

`RegisterCommand('radialmenu', function()
    if PlayerData.job.name == "police" or PlayerData.job.name == "ambulance" and not PlayerData.metadata["isdead"] and not PlayerData.metadata["inlaststand"] and not PlayerData.metadata["ishandcuffed"] and not IsPauseMenuActive() and not inRadialMenu then
            openRadial(true)
            SetCursorLocation(0.5, 0.5)
    end
end)`

This will allow police and ambulance to access F1 regardless of their state. Although, I've made mine so anyone can access F1 if in last stand but if they die then they cannot access.

**Comment by MarcusPlayz517** [comment]
gave what you sent a go, still no luck.
this is the original code line 5-10 client, no errors.
```
RegisterCommand('radialmenu', function()
    if not PlayerData.metadata["isdead"] and not PlayerData.metadata["inlaststand"] and not PlayerData.metadata["ishandcuffed"] and not IsPauseMenuActive() and not inRadialMenu then
        openRadial(true)
        SetCursorLocation(0.5, 0.5)
    end
end)
```

**Comment by NoobySloth** [comment]
Well what you could do, so this will enable everyone using it when they're dead/dying.
`RegisterCommand('radialmenu', function()
    if not PlayerData.metadata["ishandcuffed"] and not IsPauseMenuActive() and not inRadialMenu then
        openRadial(true)
        SetCursorLocation(0.5, 0.5)
    end
end)`

**Comment by MarcusPlayz517** [comment]
awesome man that worked, thank you!

**Comment by NoobySloth** [comment]
> awesome man that worked, thank you!

I'm glad to hear that! No worries mate :)
