### ISSUE TITLE
[FEATURE] Add Menu Items from Other Scripts

### ISSUE THREAD

**Issue by spaz926** [qbcore-framework/qb-radialmenu#83]
I'd love the ability for another script to add radial menu items. I'm sure this can be achieved through EventHandlers or exports.

Thanks for the consideration.

**Comment by NoobySloth** [comment]
> I'd love the ability for another script to add radial menu items. I'm sure this can be achieved through EventHandlers or exports.
> 
> Thanks for the consideration.

You could use this, just change the number to whatever.
`exports['qb-radialmenu']:AddOption(1)`

**Comment by ItsANoBrainer** [comment]
This is done in the latest version, thanks!
