### ISSUE TITLE
[QUESTION] Adding On/Off job duty button

### ISSUE THREAD

**Issue by TheOldHook** [qbcore-framework/qb-radialmenu#88]
Hi, 

Any possibilty to add a on/off button for job duty?

**Comment by nzkfc** [comment]
You can add this in by adding in an event to confitg.lua

` ["jobnamehere"] = {
        {
			id = 'toggleduty',
			title = 'Toggle Duty',
			icon = 'toggle-on',
			type = 'client',
			event = 'qb-policejob:ToggleDuty',
			shouldClose = true
		}
    }	`
