### ISSUE TITLE
Attach positioning inconsistent

### ISSUE THREAD

**Issue by sdepew** [qbcore-framework/qb-radialmenu#90]
When another player is near the stretcher and you lay on it, you will hover above it. When no one is near you lay directly on it. Similarly when you push the stretcher and another player is near the stretcher will be clipped into the ground. If no one is around it will be at the correct height. 

I submitted a pull request with a fix but it was closed. 
https://github.com/qbcore-framework/qb-radialmenu/pull/77

**Comment by ItsANoBrainer** [comment]
PR was reopened.
