### ISSUE TITLE
Vehicle Extras adding and removing

### ISSUE THREAD

**Issue by dkrandall22** [qbcore-framework/qb-radialmenu#91]
Hello! So I was attempting to add/remove extras from my patrol car and I noticed I could only remove the extras but can not add any.
Here are some clips for you!
https://medal.tv/games/gta-v/clips/gYlakt-aali5y/d1337JpqA8ey?invite=cr-MSxOQUUsMjIyNTk1ODIs
https://medal.tv/games/gta-v/clips/gYo8lxnZmupXU/d1337eRLUlEl?invite=cr-MSxVRFEsMjIyNTk1ODIs
https://medal.tv/games/gta-v/clips/gYoOvkykqDWda/d1337wYL5TKi?invite=cr-MSxuYjksMjIyNTk1ODIs

**Comment by GetBackJames** [comment]
I had the same issue but I had a few people hop in with me to test it. They can see it being removed/added but you cant for sum reason. it is best just to set the extras to true thru the pd garage when you purchase them. Or try and just use bennys.

**Comment by xnubil** [comment]
This is caused by `SetVehicleAutoRepairDisabled`. Disabling this corrects the issue, however it also ends up being free repairs for anyone toggling extras

**Comment by Branqueador** [comment]
so no fix for this i'm guessing?

**Comment by sinphoenix** [comment]
Are you still having this issue?

**Comment by sinphoenix** [comment]
Is this still an issue? i could not reproduce this error.

**Comment by lukaswe97** [comment]
Still have this issue. Other People can see the change but me not

**Comment by theenack** [comment]
This issue is still present but I can confirm setting this to false make the menu work perfectly SetVehicleAutoRepairDisabled

However as indicated that means free repairs for everyone.

**Comment by IamCodyy** [comment]
This is still an issue. Even reverting to the old code it still repairs vehicle when you reenable, even if you get the engine/body health and set them.

**Comment by theenack** [comment]
That’s always been an issue. This doesn’t stop that. It just makes adding extras work.Sent from my iPhoneOn Apr 2, 2023, at 12:09 AM, Cody ***@***.***> wrote:﻿
This is still an issue. Even reverting to the old code it still repairs vehicle when you reenable, even if you get the engine/body health and set them.
